/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/merchants/semantic-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search merchants semantically
         * @description Searches locally embedded merchant retrieval content and reranks the merchant candidates.
         */
        post: operations["semanticSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/semantic-product-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search merchant catalog products semantically
         * @description Finds relevant merchants, searches their MCP catalogs, reranks product candidates, and enriches final products with cart-ready product details.
         */
        post: operations["semanticProductSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create cart
         * @description Creates a remote MCP cart with initial items and stores the local cart snapshot.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the profile of the authenticated user, creating it from the Supabase JWT on first call (upsert-on-read).
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Updates the first name and surname of the authenticated user.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart
         * @description Returns the local cart snapshot, or refreshes it from MCP when refresh is true.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update cart
         * @description Adds items, updates line quantities, removes lines, and stores the refreshed remote cart snapshot.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API health
         * @description Returns a lightweight health response for the Meant API.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/{cartId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart checkout URL
         * @description Returns the stored checkout URL, or refreshes the cart from MCP when missing or requested.
         */
        get: operations["checkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MerchantSemanticSearchRequest: {
            query: string;
            /** Format: int32 */
            limit?: number;
        };
        MerchantSemanticSearchResponse: {
            /** Format: uuid */
            merchantId?: string;
            domain?: string;
            name?: string;
            retrievalContent?: string;
            /** Format: double */
            semanticScore?: number;
            /** Format: double */
            rerankScore?: number;
            /** Format: int32 */
            rank?: number;
        };
        MerchantSemanticProductSearchRequest: {
            query: string;
            /** Format: uuid */
            merchantId?: string;
            /** Format: int32 */
            merchantCandidateLimit?: number;
            /** Format: int32 */
            merchantLimit?: number;
            /** Format: int32 */
            productsPerMerchant?: number;
            /** Format: int32 */
            productLimit?: number;
        };
        MerchantCatalogSearchAttemptResponse: {
            /** Format: uuid */
            merchantId?: string;
            domain?: string;
            name?: string;
            /** Format: int32 */
            merchantRank?: number;
            endpoint?: string;
            /** Format: int32 */
            productCount?: number;
            error?: string;
        };
        MerchantSemanticProductResponse: {
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            merchantName?: string;
            endpoint?: string;
            /** Format: int32 */
            merchantRank?: number;
            /** Format: double */
            merchantSemanticScore?: number;
            /** Format: double */
            merchantRerankScore?: number;
            productId?: string;
            title?: string;
            descriptionHtml?: string;
            url?: string;
            imageUrl?: string;
            /** Format: int64 */
            priceMinAmount?: number;
            /** Format: int64 */
            priceMaxAmount?: number;
            priceCurrency?: string;
            available?: boolean;
            detailError?: string;
            detailDescription?: string;
            detailImageUrl?: string;
            detailImages?: components["schemas"]["ProductImageResponse"][];
            detailOptions?: components["schemas"]["ProductOptionResponse"][];
            detailPriceMin?: string;
            detailPriceMax?: string;
            detailPriceCurrency?: string;
            /** Format: int32 */
            totalVariants?: number;
            requiresSellingPlan?: boolean;
            sellingPlanGroups?: unknown[];
            selectedVariantId?: string;
            selectedVariantTitle?: string;
            selectedOptions?: components["schemas"]["ProductSelectedOptionResponse"][];
            selectedVariantPriceAmount?: string;
            selectedVariantPriceCurrency?: string;
            selectedVariantImageUrl?: string;
            selectedVariantImageAltText?: string;
            selectedVariantAvailable?: boolean;
            /** Format: int32 */
            catalogRank?: number;
            /** Format: double */
            productRerankScore?: number;
            /** Format: int32 */
            rank?: number;
        };
        MerchantSemanticProductSearchResponse: {
            merchants?: components["schemas"]["MerchantCatalogSearchAttemptResponse"][];
            products?: components["schemas"]["MerchantSemanticProductResponse"][];
        };
        ProductImageResponse: {
            url?: string;
            altText?: string;
        };
        ProductOptionResponse: {
            name?: string;
            values?: string[];
        };
        ProductSelectedOptionResponse: {
            name?: string;
            value?: string;
        };
        CartAddItemRequest: {
            productVariantId: string;
            /** Format: int32 */
            quantity?: number;
        };
        CartCreateRequest: {
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            addItems: components["schemas"]["CartAddItemRequest"][];
            buyerIdentity?: {
                [key: string]: unknown;
            };
            deliveryAddressesToAdd?: {
                [key: string]: unknown;
            }[];
            deliveryAddressesToReplace?: {
                [key: string]: unknown;
            }[];
            selectedDeliveryOptions?: {
                [key: string]: unknown;
            }[];
            discountCodes?: string[];
            giftCardCodes?: string[];
            note?: string;
        };
        CartLineResponse: {
            /** Format: uuid */
            cartLineId?: string;
            remoteCartLineId?: string;
            productId?: string;
            productTitle?: string;
            productVariantId?: string;
            variantTitle?: string;
            /** Format: int32 */
            quantity?: number;
            totalAmount?: string;
            subtotalAmount?: string;
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CartResponse: {
            /** Format: uuid */
            cartId?: string;
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            endpoint?: string;
            remoteCartId?: string;
            checkoutUrl?: string;
            instructions?: string;
            /** Format: int32 */
            totalQuantity?: number;
            totalAmount?: string;
            subtotalAmount?: string;
            currency?: string;
            active?: boolean;
            /** Format: date-time */
            remoteCreatedAt?: string;
            /** Format: date-time */
            remoteUpdatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            refreshedAt?: string;
            lines?: components["schemas"]["CartLineResponse"][];
        };
        UpdateUserProfileRequest: {
            firstName: string;
            surname?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            firstName?: string;
            surname?: string;
            profilePicturePath?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CartUpdateItemRequest: {
            /** Format: uuid */
            cartLineId?: string;
            remoteCartLineId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        CartUpdateRequest: {
            addItems?: components["schemas"]["CartAddItemRequest"][];
            updateItems?: components["schemas"]["CartUpdateItemRequest"][];
            removeCartLineIds?: string[];
            removeRemoteCartLineIds?: string[];
            buyerIdentity?: {
                [key: string]: unknown;
            };
            deliveryAddressesToAdd?: {
                [key: string]: unknown;
            }[];
            deliveryAddressesToReplace?: {
                [key: string]: unknown;
            }[];
            selectedDeliveryOptions?: {
                [key: string]: unknown;
            }[];
            discountCodes?: string[];
            giftCardCodes?: string[];
            note?: string;
        };
        /** @description Current API health status. */
        HealthResponse: {
            /**
             * @description Service name.
             * @example Meant API
             */
            service?: string;
            /**
             * @description Service status.
             * @example ok
             */
            status?: string;
            /**
             * Format: date-time
             * @description Response timestamp.
             */
            timestamp?: string;
        };
        CheckoutResponse: {
            /** Format: uuid */
            cartId?: string;
            remoteCartId?: string;
            checkoutUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    semanticSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantSemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Ranked merchant matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MerchantSemanticSearchResponse"][];
                };
            };
        };
    };
    semanticProductSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantSemanticProductSearchRequest"];
            };
        };
        responses: {
            /** @description Ranked product matches with merchant search attempts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MerchantSemanticProductSearchResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartCreateRequest"];
            };
        };
        responses: {
            /** @description Created cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileRequest"];
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: {
                /** @description Refresh the local snapshot from the remote MCP cart before returning it. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: {
                /** @description Refresh the local snapshot from the remote MCP cart before returning checkout. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart checkout URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckoutResponse"];
                };
            };
        };
    };
}
