/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/merchants/semantic-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search merchants semantically
         * @description Searches locally embedded merchant retrieval content and reranks the merchant candidates.
         */
        post: operations["semanticSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/semantic-product-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search merchant catalog products semantically
         * @description Finds relevant merchants, searches their MCP catalogs, reranks product candidates, and enriches final products with cart-ready product details.
         */
        post: operations["semanticProductSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create cart
         * @description Creates a remote MCP cart with initial items and stores the local cart snapshot.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the profile of the authenticated user, creating it from the Supabase JWT on first call (upsert-on-read).
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Updates the first name and surname of the authenticated user.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/users/me/newsletter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Update current user's newsletter subscription
         * @description Stores whether the authenticated user wants newsletter updates.
         */
        patch: operations["updateNewsletter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        trace?: never;
    };
    "/api/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart
         * @description Returns the local cart snapshot, or refreshes it from MCP when refresh is true.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update cart
         * @description Adds items, updates line quantities, removes lines, and stores the refreshed remote cart snapshot.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API health
         * @description Returns a lightweight health response for the Meant API.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/{cartId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart checkout URL
         * @description Returns the stored checkout URL, or refreshes the cart from MCP when missing or requested.
         */
        get: operations["checkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MerchantSemanticSearchRequest: {
            query: string;
            /** Format: int32 */
            limit?: number;
        };
        MerchantSemanticSearchResponse: {
            /** Format: uuid */
            merchantId?: string;
            domain?: string;
            name?: string;
            retrievalContent?: string;
            /** Format: double */
            semanticScore?: number;
            /** Format: double */
            rerankScore?: number;
            /** Format: int32 */
            rank?: number;
        };
        MerchantSemanticProductSearchRequest: {
            query: string;
            /** Format: uuid */
            merchantId?: string;
            /** Format: int32 */
            merchantCandidateLimit?: number;
            /** Format: int32 */
            merchantLimit?: number;
            /** Format: int32 */
            productsPerMerchant?: number;
            /** Format: int32 */
            productLimit?: number;
        };
        MerchantCatalogSearchAttemptResponse: {
            /** Format: uuid */
            merchantId?: string;
            domain?: string;
            name?: string;
            /** Format: int32 */
            merchantRank?: number;
            endpoint?: string;
            /** Format: int32 */
            productCount?: number;
            error?: string;
        };
        MerchantSemanticProductResponse: {
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            merchantName?: string;
            endpoint?: string;
            /** Format: int32 */
            merchantRank?: number;
            /** Format: double */
            merchantSemanticScore?: number;
            /** Format: double */
            merchantRerankScore?: number;
            productId?: string;
            title?: string;
            descriptionHtml?: string;
            url?: string;
            imageUrl?: string;
            /** Format: int64 */
            priceMinAmount?: number;
            /** Format: int64 */
            priceMaxAmount?: number;
            priceCurrency?: string;
            /** Format: int64 */
            listPriceAmount?: number;
            listPriceCurrency?: string;
            /** Format: double */
            ratingScore?: number;
            /** Format: int32 */
            reviewCount?: number;
            media?: components["schemas"]["ProductMediaResponse"][];
            categories?: components["schemas"]["ProductCategoryResponse"][];
            certifications?: string[];
            materials?: string[];
            skus?: string[];
            collections?: string[];
            attributes?: components["schemas"]["ProductAttributeResponse"][];
            available?: boolean;
            detailError?: string;
            detailDescription?: string;
            detailImageUrl?: string;
            detailImages?: components["schemas"]["ProductImageResponse"][];
            detailOptions?: components["schemas"]["ProductOptionResponse"][];
            detailPriceMin?: string;
            detailPriceMax?: string;
            detailPriceCurrency?: string;
            /** Format: int32 */
            totalVariants?: number;
            requiresSellingPlan?: boolean;
            sellingPlanGroups?: unknown[];
            selectedVariantId?: string;
            selectedVariantTitle?: string;
            selectedOptions?: components["schemas"]["ProductSelectedOptionResponse"][];
            selectedVariantPriceAmount?: string;
            selectedVariantPriceCurrency?: string;
            selectedVariantImageUrl?: string;
            selectedVariantImageAltText?: string;
            selectedVariantAvailable?: boolean;
            /** Format: int32 */
            catalogRank?: number;
            /** Format: double */
            productRerankScore?: number;
            /** Format: int32 */
            rank?: number;
        };
        MerchantSemanticProductSearchResponse: {
            merchants?: components["schemas"]["MerchantCatalogSearchAttemptResponse"][];
            products?: components["schemas"]["MerchantSemanticProductResponse"][];
        };
        ProductMediaResponse: {
            type?: string;
            url?: string;
            altText?: string;
        };
        ProductCategoryResponse: {
            value?: string;
            taxonomy?: string;
        };
        ProductAttributeResponse: {
            name?: string;
            value?: string;
        };
        ProductImageResponse: {
            url?: string;
            altText?: string;
        };
        ProductOptionResponse: {
            name?: string;
            values?: string[];
        };
        ProductSelectedOptionResponse: {
            name?: string;
            value?: string;
        };
        CartAddItemRequest: {
            productVariantId: string;
            /** Format: int32 */
            quantity?: number;
        };
        CartCreateRequest: {
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            addItems: components["schemas"]["CartAddItemRequest"][];
            buyerIdentity?: {
                [key: string]: unknown;
            };
            deliveryAddressesToAdd?: {
                [key: string]: unknown;
            }[];
            deliveryAddressesToReplace?: {
                [key: string]: unknown;
            }[];
            selectedDeliveryOptions?: {
                [key: string]: unknown;
            }[];
            discountCodes?: string[];
            giftCardCodes?: string[];
            note?: string;
        };
        CartAppliedCodeResponse: {
            /** @enum {string} */
            type?: "DISCOUNT" | "GIFT_CARD";
            code?: string;
            label?: string;
            applicable?: boolean;
            amount?: string;
            currency?: string;
        };
        CartLineResponse: {
            /** Format: uuid */
            cartLineId?: string;
            remoteCartLineId?: string;
            productId?: string;
            productTitle?: string;
            productVariantId?: string;
            variantTitle?: string;
            /** Format: int32 */
            quantity?: number;
            totalAmount?: string;
            subtotalAmount?: string;
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CartDeliveryMoneyResponse: {
            amount?: string;
            currency?: string;
        };
        CartDeliveryOptionResponse: {
            handle?: string;
            title?: string;
            description?: string;
            code?: string;
            cost?: components["schemas"]["CartDeliveryMoneyResponse"];
            deliveryMethodType?: string;
            deliveryEstimate?: string;
            estimatedDeliveryTime?: string;
            /** Format: date-time */
            estimatedDeliveryAt?: string;
            selected?: boolean;
        };
        CartDeliveryGroupResponse: {
            id?: string;
            handle?: string;
            deliveryOptions?: components["schemas"]["CartDeliveryOptionResponse"][];
            selectedDeliveryOption?: components["schemas"]["CartDeliveryOptionResponse"];
        };
        CartResponse: {
            /** Format: uuid */
            cartId?: string;
            /** Format: uuid */
            merchantId?: string;
            merchantDomain?: string;
            endpoint?: string;
            remoteCartId?: string;
            checkoutUrl?: string;
            continueUrl?: string;
            instructions?: string;
            /** Format: int32 */
            totalQuantity?: number;
            totalAmount?: string;
            subtotalAmount?: string;
            currency?: string;
            active?: boolean;
            /** Format: date-time */
            remoteCreatedAt?: string;
            /** Format: date-time */
            remoteUpdatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            refreshedAt?: string;
            appliedCodes?: components["schemas"]["CartAppliedCodeResponse"][];
            lines?: components["schemas"]["CartLineResponse"][];
            deliveryGroups?: components["schemas"]["CartDeliveryGroupResponse"][];
            messages?: components["schemas"]["CartMessageResponse"][];
        };
        CartMessageResponse: {
            code?: string;
            severity?: string;
            type?: string;
            message?: string;
            target?: string;
        };
        UpdateUserProfileRequest: {
            firstName: string;
            surname?: string;
        };
        UpdateUserNewsletterRequest: {
            newsletter: boolean;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            firstName?: string;
            surname?: string;
            profilePicturePath?: string;
            newsletter?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CartUpdateItemRequest: {
            /** Format: uuid */
            cartLineId?: string;
            remoteCartLineId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        CartUpdateRequest: {
            addItems?: components["schemas"]["CartAddItemRequest"][];
            updateItems?: components["schemas"]["CartUpdateItemRequest"][];
            removeCartLineIds?: string[];
            removeRemoteCartLineIds?: string[];
            buyerIdentity?: {
                [key: string]: unknown;
            };
            deliveryAddressesToAdd?: {
                [key: string]: unknown;
            }[];
            deliveryAddressesToReplace?: {
                [key: string]: unknown;
            }[];
            selectedDeliveryOptions?: {
                [key: string]: unknown;
            }[];
            discountCodes?: string[];
            giftCardCodes?: string[];
            note?: string;
        };
        /** @description Current API health status. */
        HealthResponse: {
            /**
             * @description Service name.
             * @example Meant API
             */
            service?: string;
            /**
             * @description Service status.
             * @example ok
             */
            status?: string;
            /**
             * Format: date-time
             * @description Response timestamp.
             */
            timestamp?: string;
        };
        /** @description Effective availability of one provider-neutral commerce operation. */
        CapabilityDecisionResponse: {
            /** @description Commerce operation being evaluated. */
            operation: "CATALOG" | "CART" | "CHECKOUT_SESSION" | "EMBEDDED_CHECKOUT" | "DIRECT_CHECKOUT_COMPLETION" | "ORDER_READS" | "ORDER_WEBHOOKS";
            /** @description Whether the selected merchant/provider integration advertises the operation. */
            advertised: boolean;
            /** @description Stable authorization, tier, and granted-scope readiness outcome. */
            authorizationStatus: "NOT_REQUIRED" | "READY" | "NOT_AUTHORIZED" | "AUTHENTICATION_DISABLED" | "TIER_NOT_GRANTED" | "MISSING_SCOPES" | "UNSUPPORTED";
            /** @description Whether product rollout enables this operation for the merchant. */
            rolloutEnabled: boolean;
            /** @description Current health of the integration selected for this operation. */
            integrationHealth: "HEALTHY" | "PENDING" | "INACTIVE" | "SUSPENDED" | "REVOKED" | "NO_INTEGRATION";
            /** @description Whether a supported fallback rail exists when the operation is ineligible. */
            fallbackSupported: boolean;
            /** @description Effective operation availability. */
            availability: "AVAILABLE" | "FALLBACK_AVAILABLE" | "UNAVAILABLE";
            /** @description Rail selected for this operation. */
            selectedRail: "PROVIDER_CATALOG" | "PROVIDER_CART" | "PROVIDER_CHECKOUT_SESSION" | "EMBEDDED_CHECKOUT" | "DIRECT_CHECKOUT_COMPLETION" | "MERCHANT_HANDOFF" | "PROVIDER_ORDER_API" | "PROVIDER_ORDER_WEBHOOK" | "NONE";
            /** @description Typed reasons explaining ineligibility or fallback selection. */
            ineligibilityReasons: ("NOT_ADVERTISED" | "AUTHORIZATION_REQUIRED" | "AUTHENTICATION_DISABLED" | "TIER_NOT_GRANTED" | "MISSING_SCOPES" | "ROLLOUT_DISABLED" | "INTEGRATION_UNHEALTHY" | "OPERATION_UNSUPPORTED" | "FALLBACK_SELECTED" | "NO_FALLBACK")[];
        };
        CheckoutResponse: {
            /**
             * Format: uuid
             * @description Meant cart identifier.
             */
            cartId?: string;
            /** @description Merchant/provider cart identifier. */
            remoteCartId?: string;
            /** @description Merchant/provider checkout identifier. */
            checkoutId?: string;
            /** @description Current provider checkout status. */
            status?: string;
            /** @description Provider checkout URL when available. */
            checkoutUrl?: string;
            /** @description Provider continuation URL when available. */
            continueUrl?: string;
            /** @description Negotiated UCP protocol version. */
            ucpVersion?: string;
            /** @description Checkout total in minor currency units. */
            totalAmountMinor?: number;
            /** @description ISO 4217 checkout currency code. */
            currency?: string;
            /** @description Whether the provider checkout state requires merchant or buyer escalation. */
            requiresEscalation?: boolean;
            /** @description Authoritative next checkout action derived from session state and execution policy. */
            nextAction: "UPDATE_CHECKOUT" | "OPEN_EMBEDDED_CHECKOUT" | "HANDOFF" | "COMPLETE_CHECKOUT" | "WAIT" | "DONE" | "RESTART" | "UNKNOWN";
            /** @description Execution rail selected by the effective checkout policy. */
            selectedRail: "PROVIDER_CATALOG" | "PROVIDER_CART" | "PROVIDER_CHECKOUT_SESSION" | "EMBEDDED_CHECKOUT" | "DIRECT_CHECKOUT_COMPLETION" | "MERCHANT_HANDOFF" | "PROVIDER_ORDER_API" | "PROVIDER_ORDER_WEBHOOK" | "NONE";
            /** @description Typed reasons that made a preferred checkout rail ineligible or selected a fallback. */
            ineligibilityReasons: ("NOT_ADVERTISED" | "AUTHORIZATION_REQUIRED" | "AUTHENTICATION_DISABLED" | "TIER_NOT_GRANTED" | "MISSING_SCOPES" | "ROLLOUT_DISABLED" | "INTEGRATION_UNHEALTHY" | "OPERATION_UNSUPPORTED" | "FALLBACK_SELECTED" | "NO_FALLBACK")[];
            /** @description Independent effective capability decisions for the merchant's commerce operations. */
            capabilities: components["schemas"]["CapabilityDecisionResponse"][];
            /** @description Provider messages for checkout guidance. */
            messages?: components["schemas"]["CheckoutMessageResponse"][];
            /**
             * @deprecated
             * @description Deprecated compatibility view derived only from direct checkout completion availability.
             */
            nativeCheckoutEnabled?: boolean;
        };
        CheckoutMessageResponse: {
            /** @description Provider message type. */
            type?: string;
            /** @description Stable provider message code. */
            code?: string;
            /** @description Provider message severity. */
            severity?: string;
            /** @description Buyer-facing provider message content. */
            content?: string;
            /** @description Payload path related to the message. */
            path?: string;
        };
        CheckoutConsentResponse: {
            /** Format: uuid */
            buyerConsentId?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        CheckoutCompletionResponse: {
            /** Format: uuid */
            cartId?: string;
            remoteCartId?: string;
            status?: "COMPLETED" | "PROCESSING" | "SCA_REQUIRED" | "CANCELED" | "HANDOFF_FALLBACK" | "RECOVERABLE_ERROR" | "UNRECOVERABLE_ERROR" | "SECURITY_LOCKED";
            checkoutId?: string;
            orderRef?: string;
            continueUrl?: string;
            messages?: string[];
            nativeAttempted?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    semanticSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantSemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Ranked merchant matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MerchantSemanticSearchResponse"][];
                };
            };
        };
    };
    semanticProductSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantSemanticProductSearchRequest"];
            };
        };
        responses: {
            /** @description Ranked product matches with merchant search attempts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MerchantSemanticProductSearchResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartCreateRequest"];
            };
        };
        responses: {
            /** @description Created cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileRequest"];
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    updateNewsletter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserNewsletterRequest"];
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: {
                /** @description Refresh the local snapshot from the remote MCP cart before returning it. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: {
                /** @description Refresh the local snapshot from the remote MCP cart before returning checkout. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                /** @description Local cart UUID. */
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart checkout URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckoutResponse"];
                };
            };
        };
    };
}
