package com.meant.api.module.user.controller.response;

import com.meant.api.module.user.constant.UserInventoryRecommendationRelationship;
import com.meant.api.module.user.service.dto.UserProductSearchProductResult;
import java.util.List;
import java.util.UUID;

public record UserProductSearchProductResponse(
        String productKey,
        String productHash,
        UUID merchantId,
        String merchantDomain,
        String merchantName,
        String endpoint,
        int merchantRank,
        double merchantSemanticScore,
        double merchantRerankScore,
        String productId,
        String title,
        String descriptionHtml,
        String url,
        String imageUrl,
        Long priceMinAmount,
        Long priceMaxAmount,
        String priceCurrency,
        Boolean available,
        String detailError,
        String detailDescription,
        String detailImageUrl,
        String detailPriceMin,
        String detailPriceMax,
        String detailPriceCurrency,
        String selectedVariantId,
        String selectedVariantTitle,
        String selectedVariantPriceAmount,
        String selectedVariantPriceCurrency,
        String selectedVariantImageUrl,
        String selectedVariantImageAltText,
        Boolean selectedVariantAvailable,
        int catalogRank,
        double productRerankScore,
        int rank,
        int matchScore,
        String whyMeantForYou,
        List<String> matchedFilterIds,
        List<String> missedFilterIds,
        UserInventoryRecommendationRelationship inventoryRelationship,
        UUID inventoryItemId,
        String inventoryItemName
) {

    public static UserProductSearchProductResponse from(UserProductSearchProductResult result) {
        return new UserProductSearchProductResponse(
                result.productKey(),
                result.productHash(),
                result.merchantId(),
                result.merchantDomain(),
                result.merchantName(),
                result.endpoint(),
                result.merchantRank(),
                result.merchantSemanticScore(),
                result.merchantRerankScore(),
                result.productId(),
                result.title(),
                result.descriptionHtml(),
                result.url(),
                result.imageUrl(),
                result.priceMinAmount(),
                result.priceMaxAmount(),
                result.priceCurrency(),
                result.available(),
                result.detailError(),
                result.detailDescription(),
                result.detailImageUrl(),
                result.detailPriceMin(),
                result.detailPriceMax(),
                result.detailPriceCurrency(),
                result.selectedVariantId(),
                result.selectedVariantTitle(),
                result.selectedVariantPriceAmount(),
                result.selectedVariantPriceCurrency(),
                result.selectedVariantImageUrl(),
                result.selectedVariantImageAltText(),
                result.selectedVariantAvailable(),
                result.catalogRank(),
                result.productRerankScore(),
                result.rank(),
                result.matchScore(),
                result.whyMeantForYou(),
                result.matchedFilterIds(),
                result.missedFilterIds(),
                result.inventoryRelationship(),
                result.inventoryItemId(),
                result.inventoryItemName()
        );
    }
}
