import type {
  CorePreferenceId,
  LocationOption,
  MerchantCoverage,
  Order,
  Preference,
  Product,
  Profile,
  Reply,
  UserAccount,
} from './types'

export const PREFERENCES: readonly Preference[] = [
  {
    id: 'organic',
    label: 'Organic',
    desc: 'Prefer certified-organic food, ingredients, and materials where relevant.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 10,
  },
  {
    id: 'non-gmo',
    label: 'Non-GMO',
    desc: 'Prefer foods and ingredients that are labeled non-GMO.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 20,
  },
  {
    id: 'gluten-free',
    label: 'Gluten-free',
    desc: 'Require products without gluten-containing ingredients.',
    category: 'food',
    polarity: 'require',
    displayOrder: 30,
  },
  {
    id: 'dairy-free',
    label: 'Dairy-free',
    desc: 'Require products without milk or dairy-derived ingredients.',
    category: 'food',
    polarity: 'require',
    displayOrder: 40,
  },
  {
    id: 'lactose-free',
    label: 'Lactose-free',
    desc: 'Prefer foods and drinks without lactose.',
    category: 'food',
    polarity: 'require',
    displayOrder: 50,
  },
  {
    id: 'vegan',
    label: 'Vegan',
    desc: 'Require products without animal-derived ingredients or materials.',
    category: 'food',
    polarity: 'require',
    displayOrder: 60,
  },
  {
    id: 'vegetarian',
    label: 'Vegetarian',
    desc: 'Prefer products suitable for a vegetarian diet.',
    category: 'food',
    polarity: 'require',
    displayOrder: 70,
  },
  {
    id: 'keto',
    label: 'Keto',
    desc: 'Prefer products compatible with a ketogenic diet.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 80,
  },
  {
    id: 'kosher',
    label: 'Kosher',
    desc: 'Require products labeled kosher.',
    category: 'food',
    polarity: 'require',
    displayOrder: 90,
  },
  {
    id: 'halal',
    label: 'Halal',
    desc: 'Require products labeled halal.',
    category: 'food',
    polarity: 'require',
    displayOrder: 100,
  },
  {
    id: 'low-sugar',
    label: 'Low sugar',
    desc: 'Prefer foods and drinks with low total or added sugar.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 110,
  },
  {
    id: 'no-added-sugar',
    label: 'No added sugar',
    desc: 'Avoid products with added sugars or sweet syrups.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 120,
  },
  {
    id: 'low-sodium',
    label: 'Low sodium',
    desc: 'Prefer foods with lower sodium content.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 130,
  },
  {
    id: 'high-protein',
    label: 'High protein',
    desc: 'Prefer products with meaningful protein content.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 140,
  },
  {
    id: 'low-carb',
    label: 'Low carb',
    desc: 'Prefer products with lower carbohydrate content.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 150,
  },
  {
    id: 'whole-foods',
    label: 'Whole foods',
    desc: 'Prefer minimally processed foods with recognizable ingredients.',
    category: 'food',
    polarity: 'prefer',
    displayOrder: 160,
  },
  {
    id: 'avoid-artificial-sweeteners',
    label: 'No artificial sweeteners',
    desc: 'Avoid artificial sweeteners such as aspartame, sucralose, or saccharin.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 170,
  },
  {
    id: 'avoid-artificial-colors',
    label: 'No artificial colors',
    desc: 'Avoid artificial colors and dyes.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 180,
  },
  {
    id: 'nut-free',
    label: 'Nut-free',
    desc: 'Avoid products containing tree nuts.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 190,
  },
  {
    id: 'peanut-free',
    label: 'Peanut-free',
    desc: 'Avoid products containing peanuts.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 200,
  },
  {
    id: 'soy-free',
    label: 'Soy-free',
    desc: 'Avoid products containing soy.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 210,
  },
  {
    id: 'egg-free',
    label: 'Egg-free',
    desc: 'Avoid products containing eggs.',
    category: 'food',
    polarity: 'avoid',
    displayOrder: 220,
  },
  {
    id: 'natural-materials',
    label: 'Natural materials',
    desc: 'Prefer clothing and home goods made from cotton, wool, linen, silk, or other natural fibers.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 300,
  },
  {
    id: 'organic-cotton',
    label: 'Organic cotton',
    desc: 'Prefer cotton products made with certified organic cotton.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 310,
  },
  {
    id: 'cotton',
    label: 'Cotton',
    desc: 'Prefer cotton as a primary material.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 320,
  },
  {
    id: 'linen',
    label: 'Linen',
    desc: 'Prefer linen as a primary material.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 330,
  },
  {
    id: 'wool',
    label: 'Wool',
    desc: 'Prefer wool as a primary material.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 340,
  },
  {
    id: 'merino-wool',
    label: 'Merino wool',
    desc: 'Prefer merino wool products.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 350,
  },
  {
    id: 'no-polyester',
    label: 'No polyester',
    desc: 'Avoid polyester and synthetic polyester blends.',
    category: 'materials',
    polarity: 'avoid',
    displayOrder: 360,
  },
  {
    id: 'no-synthetics',
    label: 'No synthetics',
    desc: 'Avoid synthetic fabrics and synthetic material blends.',
    category: 'materials',
    polarity: 'avoid',
    displayOrder: 370,
  },
  {
    id: 'no-leather',
    label: 'No leather',
    desc: 'Avoid leather and animal-hide materials.',
    category: 'materials',
    polarity: 'avoid',
    displayOrder: 380,
  },
  {
    id: 'breathable-fabrics',
    label: 'Breathable fabrics',
    desc: 'Prefer breathable fabrics for comfort and temperature regulation.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 390,
  },
  {
    id: 'durable-construction',
    label: 'Durable construction',
    desc: 'Prefer products built for long-term durability.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 400,
  },
  {
    id: 'machine-washable',
    label: 'Machine washable',
    desc: 'Prefer products that can be machine washed.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 410,
  },
  {
    id: 'plus-size-available',
    label: 'Plus size available',
    desc: 'Prefer clothing with plus size availability.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 420,
  },
  {
    id: 'petite-available',
    label: 'Petite available',
    desc: 'Prefer clothing with petite sizing availability.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 430,
  },
  {
    id: 'tall-available',
    label: 'Tall available',
    desc: 'Prefer clothing with tall sizing availability.',
    category: 'materials',
    polarity: 'prefer',
    displayOrder: 440,
  },
  {
    id: 'sustainable-brands',
    label: 'Sustainable brands',
    desc: 'Favor brands with credible sustainability practices.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 500,
  },
  {
    id: 'ethical-labor',
    label: 'Ethical labor',
    desc: 'Favor brands with credible labor and supply-chain standards.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 510,
  },
  {
    id: 'fair-trade',
    label: 'Fair trade',
    desc: 'Prefer fair-trade certified products where relevant.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 520,
  },
  {
    id: 'b-corp',
    label: 'B Corp',
    desc: 'Prefer brands with B Corp certification.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 530,
  },
  {
    id: 'recycled-materials',
    label: 'Recycled materials',
    desc: 'Prefer products made with recycled materials.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 540,
  },
  {
    id: 'recyclable-packaging',
    label: 'Recyclable packaging',
    desc: 'Prefer packaging that is recyclable.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 550,
  },
  {
    id: 'plastic-free-packaging',
    label: 'Plastic-free packaging',
    desc: 'Prefer packaging without plastic.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 560,
  },
  {
    id: 'low-waste',
    label: 'Low waste',
    desc: 'Prefer low-waste products and packaging.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 570,
  },
  {
    id: 'carbon-neutral',
    label: 'Carbon neutral',
    desc: 'Prefer products or brands with credible carbon-neutral claims.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 580,
  },
  {
    id: 'cruelty-free',
    label: 'Cruelty-free',
    desc: 'Prefer products not tested on animals.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 590,
  },
  {
    id: 'locally-made',
    label: 'Locally made',
    desc: "Prefer products made close to the buyer's region where available.",
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 600,
  },
  {
    id: 'made-in-usa',
    label: 'Made in USA',
    desc: 'Prefer products made in the United States.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 610,
  },
  {
    id: 'secondhand-or-refurbished',
    label: 'Secondhand or refurbished',
    desc: 'Prefer secondhand, refurbished, renewed, or pre-owned options.',
    category: 'sustainability',
    polarity: 'prefer',
    displayOrder: 620,
  },
  {
    id: 'fragrance-free',
    label: 'Fragrance-free',
    desc: 'Avoid added fragrance or perfume.',
    category: 'personal-care',
    polarity: 'avoid',
    displayOrder: 700,
  },
  {
    id: 'sensitive-skin',
    label: 'Sensitive skin',
    desc: 'Prefer products suitable for sensitive skin.',
    category: 'personal-care',
    polarity: 'prefer',
    displayOrder: 710,
  },
  {
    id: 'hypoallergenic',
    label: 'Hypoallergenic',
    desc: 'Prefer products labeled hypoallergenic.',
    category: 'personal-care',
    polarity: 'prefer',
    displayOrder: 720,
  },
  {
    id: 'non-toxic',
    label: 'Non-toxic',
    desc: 'Prefer products positioned around lower-toxicity ingredients or materials.',
    category: 'personal-care',
    polarity: 'prefer',
    displayOrder: 730,
  },
  {
    id: 'paraben-free',
    label: 'Paraben-free',
    desc: 'Avoid parabens in personal care products.',
    category: 'personal-care',
    polarity: 'avoid',
    displayOrder: 740,
  },
  {
    id: 'sulfate-free',
    label: 'Sulfate-free',
    desc: 'Avoid sulfates in personal care products.',
    category: 'personal-care',
    polarity: 'avoid',
    displayOrder: 750,
  },
  {
    id: 'phthalate-free',
    label: 'Phthalate-free',
    desc: 'Avoid phthalates in personal care products.',
    category: 'personal-care',
    polarity: 'avoid',
    displayOrder: 760,
  },
  {
    id: 'reef-safe',
    label: 'Reef-safe',
    desc: 'Prefer sunscreen and personal care products positioned as reef-safe.',
    category: 'personal-care',
    polarity: 'prefer',
    displayOrder: 770,
  },
  {
    id: 'best-value',
    label: 'Best quality in budget',
    desc: 'Prefer the strongest quality-to-price tradeoff.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 800,
  },
  {
    id: 'budget-friendly',
    label: 'Budget-friendly',
    desc: 'Prefer lower-priced products.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 810,
  },
  {
    id: 'premium-quality',
    label: 'Premium quality',
    desc: 'Prefer premium, higher-quality products even when they cost more.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 820,
  },
  {
    id: 'long-lasting',
    label: 'Long lasting',
    desc: 'Prefer products known for longevity and durability.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 830,
  },
  {
    id: 'highly-rated',
    label: 'Strong reviews',
    desc: 'Prefer products with strong ratings and positive customer feedback.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 840,
  },
  {
    id: 'many-reviews',
    label: 'Many reviews',
    desc: 'Prefer products with a substantial review count.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 850,
  },
  {
    id: 'expert-recommended',
    label: 'Expert recommended',
    desc: 'Prefer products recommended by credible experts or publications.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 860,
  },
  {
    id: 'minimalist-design',
    label: 'Minimalist design',
    desc: 'Prefer simple, understated product design.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 870,
  },
  {
    id: 'easy-returns',
    label: 'Easy returns',
    desc: 'Prefer products or merchants with easy return policies.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 880,
  },
  {
    id: 'warranty-included',
    label: 'Warranty included',
    desc: 'Prefer products with a warranty or strong guarantee.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 890,
  },
  {
    id: 'fast-shipping',
    label: 'Fast shipping',
    desc: 'Prefer products that can arrive quickly.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 900,
  },
  {
    id: 'free-shipping',
    label: 'Free shipping',
    desc: 'Prefer products or merchants with free shipping.',
    category: 'shopping',
    polarity: 'prefer',
    displayOrder: 910,
  },
  {
    id: 'avoid-subscriptions',
    label: 'No subscriptions',
    desc: 'Avoid products that require subscriptions or recurring purchases.',
    category: 'shopping',
    polarity: 'avoid',
    displayOrder: 920,
  },
  {
    id: 'usb-c',
    label: 'USB-C',
    desc: 'Prefer products with USB-C compatibility.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1000,
  },
  {
    id: 'usb-a',
    label: 'USB-A',
    desc: 'Prefer products with USB-A compatibility.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1010,
  },
  {
    id: 'hdmi',
    label: 'HDMI',
    desc: 'Prefer products with HDMI compatibility.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1020,
  },
  {
    id: 'wireless',
    label: 'Wireless',
    desc: 'Prefer wireless products or wireless connectivity.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1030,
  },
  {
    id: 'bluetooth',
    label: 'Bluetooth',
    desc: 'Prefer Bluetooth-compatible products.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1040,
  },
  {
    id: 'rechargeable',
    label: 'Rechargeable',
    desc: 'Prefer rechargeable products.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1050,
  },
  {
    id: 'energy-efficient',
    label: 'Energy efficient',
    desc: 'Prefer products with lower energy usage.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1060,
  },
  {
    id: 'repairable',
    label: 'Repairable',
    desc: 'Prefer products that are repairable or have replaceable parts.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1070,
  },
  {
    id: 'compatible-apple',
    label: 'Apple compatible',
    desc: 'Prefer products compatible with Apple devices.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1080,
  },
  {
    id: 'compatible-android',
    label: 'Android compatible',
    desc: 'Prefer products compatible with Android devices.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1090,
  },
  {
    id: 'compact',
    label: 'Compact',
    desc: 'Prefer compact products that do not take much space.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1100,
  },
  {
    id: 'travel-friendly',
    label: 'Travel friendly',
    desc: 'Prefer products that are portable and suitable for travel.',
    category: 'technology',
    polarity: 'prefer',
    displayOrder: 1110,
  },
  {
    id: 'space-saving',
    label: 'Space saving',
    desc: 'Prefer products that save space at home.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1200,
  },
  {
    id: 'quiet-operation',
    label: 'Quiet operation',
    desc: 'Prefer products that operate quietly.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1210,
  },
  {
    id: 'dishwasher-safe',
    label: 'Dishwasher safe',
    desc: 'Prefer products that can be cleaned in a dishwasher.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1220,
  },
  {
    id: 'easy-clean',
    label: 'Easy clean',
    desc: 'Prefer products that are easy to clean.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1230,
  },
  {
    id: 'child-safe',
    label: 'Child safe',
    desc: 'Prefer products suitable for homes with children.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1240,
  },
  {
    id: 'pet-safe',
    label: 'Pet safe',
    desc: 'Prefer products suitable for homes with pets.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1250,
  },
  {
    id: 'unscented',
    label: 'Unscented',
    desc: 'Avoid added scents in home or personal products.',
    category: 'home',
    polarity: 'avoid',
    displayOrder: 1260,
  },
  {
    id: 'low-maintenance',
    label: 'Low maintenance',
    desc: 'Prefer products that require little ongoing care.',
    category: 'home',
    polarity: 'prefer',
    displayOrder: 1270,
  },
  {
    id: 'crypto',
    label: 'Crypto',
    desc: 'Prefer tasteful crypto, bitcoin, trading, or market-culture references when the theme is relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2000,
  },
  {
    id: 'investing',
    label: 'Investing',
    desc: 'Prefer products with investing, markets, or finance themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2010,
  },
  {
    id: 'startups',
    label: 'Startups',
    desc: 'Prefer products with founder, builder, startup, or entrepreneurship themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2020,
  },
  {
    id: 'ai',
    label: 'AI',
    desc: 'Prefer products with artificial intelligence or future-tech themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2030,
  },
  {
    id: 'coding',
    label: 'Coding',
    desc: 'Prefer developer, programming, software, or coding-culture themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2040,
  },
  {
    id: 'gaming',
    label: 'Gaming',
    desc: 'Prefer products with gaming, esports, or game-culture themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2050,
  },
  {
    id: 'retro-gaming',
    label: 'Retro gaming',
    desc: 'Prefer products with retro console, arcade, pixel-art, or classic game themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2060,
  },
  {
    id: 'anime-manga',
    label: 'Anime and manga',
    desc: 'Prefer products with anime, manga, or Japanese pop-culture themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2070,
  },
  {
    id: 'streetwear',
    label: 'Streetwear',
    desc: 'Prefer streetwear styling, graphics, silhouettes, or culture when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2080,
  },
  {
    id: 'sneakers',
    label: 'Sneakers',
    desc: 'Prefer sneaker culture, footwear-inspired details, or products that pair well with sneakers when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2090,
  },
  {
    id: 'coffee',
    label: 'Coffee',
    desc: 'Prefer coffee, espresso, cafe, or brewing themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2100,
  },
  {
    id: 'fitness',
    label: 'Fitness',
    desc: 'Prefer gym, training, strength, or active-lifestyle themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2110,
  },
  {
    id: 'running',
    label: 'Running',
    desc: 'Prefer running, race, pace, or endurance themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2120,
  },
  {
    id: 'cycling',
    label: 'Cycling',
    desc: 'Prefer cycling, bike, road, gravel, or commuter-bike themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2130,
  },
  {
    id: 'hiking',
    label: 'Hiking',
    desc: 'Prefer hiking, trail, camping, or outdoor adventure themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2140,
  },
  {
    id: 'travel',
    label: 'Travel',
    desc: 'Prefer travel, city-break, airport, or world-explorer themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2150,
  },
  {
    id: 'books',
    label: 'Books',
    desc: 'Prefer books, libraries, reading, or literary themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2160,
  },
  {
    id: 'music',
    label: 'Music',
    desc: 'Prefer music, records, instruments, audio, or concert themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2170,
  },
  {
    id: 'movies',
    label: 'Movies',
    desc: 'Prefer cinema, film, director, or movie-culture themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2180,
  },
  {
    id: 'pets',
    label: 'Pets',
    desc: 'Prefer pet-friendly, dog, cat, or animal-companion themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2190,
  },
  {
    id: 'plants',
    label: 'Plants',
    desc: 'Prefer houseplant, gardening, botanical, or grower themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2200,
  },
  {
    id: 'cars',
    label: 'Cars',
    desc: 'Prefer automotive, car culture, motorsport, or garage themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2210,
  },
  {
    id: 'football',
    label: 'Football',
    desc: 'Prefer football or gridiron themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2220,
  },
  {
    id: 'basketball',
    label: 'Basketball',
    desc: 'Prefer basketball, court, hoops, or pickup-game themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2230,
  },
  {
    id: 'soccer',
    label: 'Soccer',
    desc: 'Prefer soccer, football-club, pitch, or matchday themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2240,
  },
  {
    id: 'golf',
    label: 'Golf',
    desc: 'Prefer golf, clubhouse, course, or weekend-round themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2250,
  },
  {
    id: 'wellness',
    label: 'Wellness',
    desc: 'Prefer wellness, recovery, mindfulness, spa, or self-care themes when relevant.',
    category: 'interests',
    polarity: 'prefer',
    displayOrder: 2260,
  },
]

export const PROFILE: Profile = {
  name: 'Meant',
  summary: 'organic food, natural-material clothing, and products people actually love.',
}

export const DEFAULT_USER: UserAccount = {
  name: PROFILE.name,
  email: '',
  avatar: null,
  avatarPath: null,
  newsletter: false,
}

export const PRODUCTS: readonly Product[] = [
  {
    id: 'cereal',
    name: 'Sprouted Oat & Almond Cereal',
    brand: 'Wholegrain Co.',
    category: 'Groceries',
    tone: '#e9ede8',
    match: 96,
    priceFrom: 7.4,
    priceCurrency: 'USD',
    merchants: 4,
    satisfies: ['organic', 'low-sugar', 'highly-rated'],
    misses: [],
    note: 'Organic, 3g sugar per serving, and the highest-rated cereal in your saved categories.',
    pros: ['No refined sugar', 'Whole sprouted grains', 'Recyclable packaging'],
    cons: ['Pricier than supermarket own-brand'],
    review: {
      score: 4.8,
      count: 2140,
      insight:
        "Reviewers consistently mention it keeps them full until lunch and isn't overly sweet.",
    },
    offers: [
      { merchant: 'Whole Foods', price: 7.4, priceCurrency: 'USD', delivery: 'Tomorrow' },
      { merchant: 'Thrive Market', price: 7.9, priceCurrency: 'USD', delivery: '2 days' },
      { merchant: 'iHerb', price: 8.2, priceCurrency: 'USD', delivery: '3 days' },
    ],
  },
  {
    id: 'tee',
    name: 'Heavyweight Organic Cotton Tee',
    brand: 'Field & Loom',
    category: 'Clothing',
    tone: '#e7ebef',
    match: 94,
    priceFrom: 38,
    priceCurrency: 'USD',
    merchants: 3,
    audiences: ['unisex'],
    satisfies: [
      'natural-materials',
      'no-polyester',
      'sustainable-brands',
      'organic',
      'organic-cotton',
    ],
    misses: [],
    note: '100% organic cotton, no synthetic blends, from a brand with verified sustainability practices.',
    pros: ['240gsm organic cotton', 'GOTS certified', 'Holds shape after wash'],
    cons: ['Runs slightly large'],
    review: {
      score: 4.7,
      count: 860,
      insight: 'Buyers love the weight and fit; a few mention sizing up is unnecessary.',
    },
    offers: [
      { merchant: 'Field & Loom', price: 38, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Everlane', price: 42, priceCurrency: 'USD', delivery: '2 days' },
    ],
  },
  {
    id: 'brewer',
    name: 'Precision Pour-Over Brewer',
    brand: 'Kuro',
    category: 'Home & Kitchen',
    tone: '#eceae7',
    match: 91,
    priceFrom: 149,
    priceCurrency: 'USD',
    merchants: 5,
    satisfies: ['highly-rated', 'best-value', 'quiet-operation'],
    misses: [],
    note: 'The best-reviewed brewer in your budget, with precise temperature control without the prosumer price.',
    pros: ['Exact temp control', 'Quiet operation', '10-year brand warranty'],
    cons: ['Takes counter space'],
    review: {
      score: 4.6,
      count: 3320,
      insight: 'Owners praise consistency cup-to-cup; the main complaint is its footprint.',
    },
    offers: [
      { merchant: 'Kuro', price: 149, priceCurrency: 'USD', delivery: '4 days' },
      { merchant: 'Williams Sonoma', price: 159, priceCurrency: 'USD', delivery: '2 days' },
      { merchant: 'Amazon', price: 154, priceCurrency: 'USD', delivery: 'Tomorrow' },
    ],
  },
  {
    id: 'oil',
    name: 'Cold-Pressed Extra Virgin Olive Oil',
    brand: 'Casa Verde',
    category: 'Groceries',
    tone: '#eaede6',
    match: 89,
    priceFrom: 18.5,
    priceCurrency: 'USD',
    merchants: 3,
    satisfies: ['organic', 'highly-rated'],
    misses: [],
    note: 'Single-estate, organic, and an exceptional review profile for everyday cooking.',
    pros: ['Single-origin', 'Harvest date on bottle', 'Low acidity'],
    cons: ['Glass bottle is heavy to ship'],
    review: {
      score: 4.9,
      count: 1180,
      insight: 'Described as fresh and peppery; reviewers repurchase frequently.',
    },
    offers: [
      { merchant: 'Casa Verde', price: 18.5, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Thrive Market', price: 19.2, priceCurrency: 'USD', delivery: '2 days' },
    ],
  },
  {
    id: 'sweater',
    name: 'Merino Crew Sweater',
    brand: 'Northbound',
    category: 'Clothing',
    tone: '#e8ebee',
    match: 92,
    priceFrom: 95,
    priceCurrency: 'USD',
    merchants: 4,
    audiences: ['women'],
    satisfies: ['natural-materials', 'no-polyester', 'sustainable-brands', 'merino-wool'],
    misses: [],
    note: 'Pure merino wool, no synthetic blend, from a B-Corp certified brand.',
    pros: ['Temperature regulating', 'No-itch fine merino', 'Mulesing-free wool'],
    cons: ['Hand wash recommended'],
    review: {
      score: 4.7,
      count: 540,
      insight: 'Praised for softness and warmth without bulk.',
    },
    offers: [
      { merchant: 'Northbound', price: 95, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Wool&', price: 110, priceCurrency: 'USD', delivery: '4 days' },
    ],
  },
  {
    id: 'runners',
    name: 'Recycled Knit Runners',
    brand: 'Stride Lab',
    category: 'Footwear',
    tone: '#eceaea',
    match: 71,
    priceFrom: 120,
    priceCurrency: 'USD',
    merchants: 3,
    audiences: ['unisex'],
    satisfies: ['sustainable-brands', 'highly-rated', 'recycled-materials'],
    misses: ['no-polyester'],
    note: 'Strong on sustainability and reviews, but the knit upper contains recycled polyester.',
    pros: ['Made from recycled ocean plastic', 'Very light', 'Machine washable'],
    cons: ['Contains polyester', 'Narrow toe box'],
    review: {
      score: 4.5,
      count: 2780,
      insight: 'Loved for comfort and weight; some note the synthetic upper runs warm.',
    },
    offers: [
      { merchant: 'Stride Lab', price: 120, priceCurrency: 'USD', delivery: '2 days' },
      { merchant: 'Amazon', price: 124, priceCurrency: 'USD', delivery: 'Tomorrow' },
    ],
  },
  {
    id: 'laptop',
    name: 'Aero 13 Ultralight Laptop',
    brand: 'Lumen',
    category: 'Tech',
    tone: '#e9eaee',
    match: 90,
    priceFrom: 1099,
    priceCurrency: 'USD',
    merchants: 2,
    satisfies: ['highly-rated', 'best-value', 'usb-c'],
    misses: [],
    provides: ['usb-c'],
    note: 'The best-reviewed ultralight in your budget. Note: it has USB-C ports only.',
    pros: ['18-hour battery', '1.1kg', 'USB-C / Thunderbolt'],
    cons: ['No USB-A or HDMI ports'],
    review: {
      score: 4.7,
      count: 5120,
      insight: 'Praised for battery and weight; a few note the USB-C-only ports need adapters.',
    },
    offers: [
      { merchant: 'Lumen Store', price: 1099, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Amazon', price: 1119, priceCurrency: 'USD', delivery: 'Tomorrow' },
    ],
  },
  {
    id: 'monitor',
    name: '27" 4K USB-C Monitor',
    brand: 'Crisp',
    category: 'Tech',
    tone: '#e8ebee',
    match: 88,
    priceFrom: 389,
    priceCurrency: 'USD',
    merchants: 2,
    satisfies: ['highly-rated', 'best-value', 'usb-c'],
    misses: [],
    needs: 'usb-c',
    note: 'Single-cable USB-C monitor that charges your laptop while you work.',
    pros: ['4K at 60Hz', 'USB-C single cable', '90W passthrough charging'],
    cons: ['Stand takes desk space'],
    review: {
      score: 4.6,
      count: 1840,
      insight: 'Reviewers love the single-cable setup and color accuracy.',
    },
    offers: [
      { merchant: 'Crisp Store', price: 389, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Amazon', price: 399, priceCurrency: 'USD', delivery: 'Tomorrow' },
    ],
  },
  {
    id: 'drive',
    name: 'Rugged 2TB Portable Drive',
    brand: 'Hold',
    category: 'Tech',
    tone: '#eceae9',
    match: 84,
    priceFrom: 125,
    priceCurrency: 'USD',
    merchants: 2,
    satisfies: ['highly-rated', 'usb-c', 'hdmi'],
    misses: [],
    needs: 'usb-a',
    note: 'Fast, shock-proof backup drive that connects over USB-A.',
    pros: ['IP54 dust and water resistant', '5-year warranty', '1050MB/s'],
    cons: ['USB-A connector only'],
    review: {
      score: 4.6,
      count: 990,
      insight: 'Trusted for durability; the USB-A-only cable trips up newer-laptop owners.',
    },
    offers: [
      { merchant: 'Amazon', price: 129, priceCurrency: 'USD', delivery: 'Tomorrow' },
      { merchant: 'Hold Store', price: 125, priceCurrency: 'USD', delivery: '4 days' },
    ],
  },
  {
    id: 'adapter',
    name: 'USB-C to USB-A Adapter',
    brand: 'Lumen',
    category: 'Tech',
    tone: '#eaeaec',
    match: 86,
    priceFrom: 19,
    priceCurrency: 'USD',
    merchants: 2,
    satisfies: ['best-value', 'usb-c', 'compact', 'travel-friendly'],
    misses: [],
    needs: 'usb-c',
    provides: ['usb-a'],
    note: 'Plugs into USB-C and adds a full-size USB-A port for older accessories.',
    pros: ['Plug-and-play', 'Aluminium body', 'Pocket-sized'],
    cons: ['One port only'],
    review: {
      score: 4.5,
      count: 3400,
      insight: 'Reviewers call it a must-have for USB-C-only laptops.',
    },
    offers: [
      { merchant: 'Lumen Store', price: 19, priceCurrency: 'USD', delivery: '3 days' },
      { merchant: 'Amazon', price: 21, priceCurrency: 'USD', delivery: 'Tomorrow' },
    ],
  },
]

export const PROMPTS: readonly string[] = [
  'Find me a healthy breakfast cereal',
  'A good cotton T-shirt under $50',
  'Quiet coffee machine under $200',
  'Fragrance-free sunscreen for sensitive skin',
]

export const REPLIES: Readonly<Record<string, Reply>> = {
  default: {
    text: "Here's what I found, filtered to your preferences. I've hidden anything that clashes with your profile and surfaced the strongest matches first.",
    ids: ['cereal', 'tee', 'brewer', 'oil', 'sweater', 'runners'],
  },
  cereal: {
    text: "For breakfast I'd start with the Sprouted Oat & Almond Cereal. It's organic, just 3g of sugar, and the best-reviewed option in your saved categories.",
    ids: ['cereal', 'oil'],
  },
  tee: {
    text: 'Under $50, the Heavyweight Organic Cotton Tee is the cleanest match: 100% organic cotton, no synthetic blend, from a sustainable brand.',
    ids: ['tee', 'sweater'],
  },
  brewer: {
    text: 'The Precision Pour-Over Brewer is the best-reviewed machine inside your budget: precise temperature control without the prosumer price.',
    ids: ['brewer'],
  },
}

export const LOCATIONS: readonly LocationOption[] = [
  {
    country: 'United States',
    code: 'US',
    cities: [
      'New York',
      'Los Angeles',
      'San Francisco',
      'Chicago',
      'Austin',
      'Seattle',
      'Denver',
      'Miami',
    ],
  },
  {
    country: 'United Kingdom',
    code: 'GB',
    cities: ['London', 'Manchester', 'Edinburgh', 'Bristol'],
  },
  {
    country: 'Canada',
    code: 'CA',
    cities: ['Toronto', 'Vancouver', 'Montreal'],
  },
  {
    country: 'Germany',
    code: 'DE',
    cities: ['Berlin', 'Munich', 'Hamburg'],
  },
  {
    country: 'Australia',
    code: 'AU',
    cities: ['Sydney', 'Melbourne', 'Brisbane'],
  },
]

export const MERCHANTS: Readonly<Record<string, MerchantCoverage>> = {
  Amazon: { ships: 'global' },
  iHerb: { ships: 'global' },
  'Stride Lab': { ships: 'global' },
  'Thrive Market': { ships: ['US'] },
  'Whole Foods': {
    ships: ['US'],
    cities: ['New York', 'Los Angeles', 'San Francisco', 'Chicago', 'Austin', 'Seattle'],
  },
  'Field & Loom': { ships: ['US', 'CA', 'GB'] },
  Everlane: { ships: ['US', 'CA', 'GB', 'DE'] },
  Kuro: { ships: ['US', 'CA', 'GB', 'DE', 'AU'] },
  'Williams Sonoma': { ships: ['US', 'CA'] },
  'Casa Verde': { ships: ['US', 'GB', 'DE'] },
  Northbound: { ships: ['US', 'CA', 'GB', 'AU'] },
  'Wool&': { ships: ['US'] },
  'Lumen Store': { ships: ['US', 'CA', 'GB', 'DE', 'AU'] },
  'Crisp Store': { ships: ['US', 'GB', 'DE'] },
  'Hold Store': { ships: ['US', 'CA'] },
}

export const DEFAULT_SAVED: readonly Product[] = PRODUCTS.filter((product) =>
  ['cereal', 'tee', 'brewer'].includes(product.id),
)

export const DEFAULT_SAVED_IDS: readonly Product['id'][] = ['cereal', 'tee', 'brewer']

export const DEFAULT_ORDERS: readonly Order[] = [
  {
    id: 'MNT-4192',
    date: '2026-06-11',
    status: 'In transit',
    statusNote: 'Out for delivery: arrives Jun 16.',
    items: [{ id: 'brewer', merchant: 'Kuro', qty: 1 }],
    saved: 0,
    savedNote: '',
  },
  {
    id: 'MNT-3947',
    date: '2026-05-21',
    status: 'Delivered',
    statusNote: 'Delivered May 25.',
    items: [
      { id: 'tee', merchant: 'Field & Loom', qty: 2 },
      { id: 'sweater', merchant: 'Northbound', qty: 1 },
    ],
    saved: 0,
    savedNote: '',
  },
  {
    id: 'MNT-3610',
    date: '2026-04-28',
    status: 'Delivered',
    statusNote: 'Delivered May 1.',
    items: [
      { id: 'cereal', merchant: 'Whole Foods', qty: 2 },
      { id: 'oil', merchant: 'Casa Verde', qty: 1 },
    ],
    saved: 0,
    savedNote: '',
  },
  {
    id: 'MNT-3158',
    date: '2026-03-09',
    status: 'Delivered',
    statusNote: 'Delivered Mar 13.',
    items: [
      { id: 'laptop', merchant: 'Lumen Store', qty: 1 },
      { id: 'adapter', merchant: 'Lumen Store', qty: 1 },
    ],
    saved: 0,
    savedNote: '',
  },
]

export const DEFAULT_PREFERENCE_IDS: readonly CorePreferenceId[] = [
  'organic',
  'natural-materials',
  'no-polyester',
  'highly-rated',
  'sustainable-brands',
  'best-value',
  'low-sugar',
]

export const CORE_PREFERENCE_IDS: readonly CorePreferenceId[] = PREFERENCES.map(
  (preference) => preference.id,
)
