package com.meant.api.module.merchant.constant;

public enum CapabilityIneligibilityReason {
    NOT_ADVERTISED,
    AUTHORIZATION_REQUIRED,
    AUTHENTICATION_DISABLED,
    TIER_NOT_GRANTED,
    MISSING_SCOPES,
    ROLLOUT_DISABLED,
    INTEGRATION_UNHEALTHY,
    OPERATION_UNSUPPORTED,
    MERCHANT_REDIRECT_REQUIRED,
    FALLBACK_SELECTED,
    NO_FALLBACK
}
